PAIR INTRO A PANDAS:

In [1]:
import pandas as pd
import numpy as np
import random

 
1. ¿Qué diferencia hay entre una Serie y un DataFrame?

 Series:
- es una estructura unidimensional (array 1d)
- contiene UN tipo de dato.
- Tiene indice -> pueden ser de distintos tipos (pueden ser numericas, int, ...)
- Propiedades: 
        -> .values
        -> .index
        -> .shape
        -> .size
        -> .dtype

 DATAFRAMES:

- Dos dimensiones
- Cada columna tiene un tipo de dato
- Tiene indice.
- Propiedades:
    -> .size
    -> .shape
    -> .columns

In [2]:
# Es el turno de los DataFrames
# Crea un array de dos dimensiones con 4 filas y 3 columnas.

array = np.random.randint(1,50, (4,3))

print(f"El array bidimensional creado a partir del método np.random.randint(): \n  {array} \n")


El array bidimensional creado a partir del método np.random.randint(): 
  [[24 32  3]
 [40 31 11]
 [36  8  8]
 [ 3  5 39]] 



In [3]:
#Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

df_paises = pd.DataFrame(array)

In [4]:
df_paises

0   1   2
0  24  32   3
1  40  31  11
2  36   8   8
3   3   5  39

In [5]:
paises = ["España", "Francia", "Italia"]

df_paises = pd.DataFrame(array, columns=[paises])

df_paises

España Francia Italia
0     24      32      3
1     40      31     11
2     36       8      8
3      3       5     39

In [6]:
# Descarga el archivo "medallas" y carga el DataFrame.

df_medallas = pd.read_csv("medallas.csv", index_col = 0) # tb podemos poner index_col= "País"

df_medallas

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [7]:
# Usando el loc extrae todas las columnas de la fila de Tailandia.

df_medallas.loc[df_medallas["País"] == "Tailandia"]

País  Oro  Plata  Bronce
7  Tailandia  132    175     278

In [8]:
#Usando el loc extrae todas las columnas de China e Irán.

df_medallas.loc[df_medallas["País"] == "China"] 

País   Oro  Plata  Bronce
1  China  1473    994     720

In [9]:
df_medallas.loc[df_medallas["País"] == "Irán"] 

País  Oro  Plata  Bronce
4  Irán  179    181     197

In [10]:
"""df_medallas = df_medallas.loc[(df_medallas["País"] == "China") & (df_medallas["País"]=="tailandia")]
df_medallas"""

'df_medallas = df_medallas.loc[(df_medallas["País"] == "China") & (df_medallas["País"]=="tailandia")]\ndf_medallas'

In [11]:
df_medallas.loc[[1,4]]

País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197

In [12]:
# Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

df_medallas.loc[[1,4]]

País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197

In [13]:
# Usando el iloc extrae la información de la India. Devolved todas las columnas.

df_medallas.iloc[5:6]

País  Oro  Plata  Bronce
6  India  154    202     315

In [14]:
# Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

df_medallas.iloc[1::2]

País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235

In [15]:
# Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

df_medallas.iloc[1::2, [1,2,3]]

Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235

In [16]:
# ¿Qué país consiguió más de 200 medallas de oro?

df_medallas ["Oro"] > 200

1      True
2      True
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
Name: Oro, dtype: bool

In [17]:
df_medallas[df_medallas["Oro"] > 200] 

País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827

In [18]:
# ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

df_medallas[(df_medallas["Oro"] > 200) & (df_medallas["Plata"] > 1000)]

País   Oro  Plata  Bronce
2  Japón  1032   1037     985

In [19]:
# ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

df_medallas[(df_medallas["Oro"] > 200) & (df_medallas["Bronce"] > 700)]


País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827

In [20]:
# Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

df_medallas["Total"] = df_medallas["Oro"] + df_medallas["Plata"] + df_medallas ["Bronce"]
df_medallas


País   Oro  Plata  Bronce  Total
1             China  1473    994     720   3187
2             Japón  1032   1037     985   3054
3     Corea del Sur   745    663     827   2235
4              Irán   179    181     197    557
5        Kazajistán   155    158     224    537
6             India   154    202     315    671
7         Tailandia   132    175     278    585
8         Indonesia   112    131     240    483
9      China Taipéi    99    144     276    519
10  Corea del Norte    91    120     235    446

In [21]:
# 3.Momento de trabajar con Series. Contesta a las siguientes preguntas:
# Crea dos listas:
# Una que se llame "valores" que tenga 7 números aleatorios.
# Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

valores = np.random.randint(1,50, 7)

indices = ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"]


In [22]:
"""A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie
y la variable indices sean los índices de la Serie."""

serie_dias = pd.Series(valores, index = indices )
serie_dias

lunes         6
martes       18
miercoles    42
jueves       18
viernes      15
sabado       31
domingo      30
dtype: int32

In [23]:
"""A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip 
que nos permite iterar por dos listas a la vez. Más información sobre este método aquí."""

diccionario = {}

In [24]:
dict(zip(indices,valores)) # nos piden diccionario

{'lunes': np.int32(6),
 'martes': np.int32(18),
 'miercoles': np.int32(42),
 'jueves': np.int32(18),
 'viernes': np.int32(15),
 'sabado': np.int32(31),
 'domingo': np.int32(30)}

In [25]:
diccionario ={}
for e in zip(indices,valores):
    diccionario[e[0]]= e[1]
   
diccionario

{'lunes': np.int32(6),
 'martes': np.int32(18),
 'miercoles': np.int32(42),
 'jueves': np.int32(18),
 'viernes': np.int32(15),
 'sabado': np.int32(31),
 'domingo': np.int32(30)}

In [ ]:
zip(indices,valores) 

In [ ]:
"""Crea una Serie con el diccionario creado en el punto anterior."""

In [28]:
serie_dias=pd.Series(diccionario)
serie_dias

lunes         6
martes       18
miercoles    42
jueves       18
viernes      15
sabado       31
domingo      30
dtype: int32

In [ ]:
"""¿Qué forma tiene esta última Serie?"""

In [29]:
serie_dias.shape

(7,)

In [30]:
"""¿Qué tipo de datos tiene?"""

serie_dias.dtype

dtype('int32')

In [31]:
"""¿Qué tamaño tiene?"""

serie_dias.size

7

In [ ]:
"""¿Cuáles son los índices de la Serie?"""

In [32]:
serie_dias.index

Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')

In [33]:
"""¿Y los values?"""

serie_dias.values

array([ 6, 18, 42, 18, 15, 31, 30], dtype=int32)

In [37]:
"""Extrae el valor para el índice "lunes"""

serie_dias[0]

C:\Users\InvitadoLaptop\AppData\Local\Temp\ipykernel_12800\2126384030.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  serie_dias[0]


np.int32(6)

In [40]:
serie_dias["lunes"]

np.int32(6)

In [43]:
"""Extrae el valor para el índice "lunes", "martes" y "miércoles"."""

serie_dias[["lunes", "martes", "miercoles"]]

lunes         6
martes       18
miercoles    42
dtype: int32

In [44]:
"""Extrae el valor para el índice "lunes" y "domingo"."""

serie_dias[["lunes", "domingo"]]

lunes       6
domingo    30
dtype: int32

In [ ]:
# Más ejercicios de loc e iloc
#Para realizar estos ejercicios deberéis usar el conjunto de datos de world-data-2023-part1.csv.

In [49]:
"""Selecciona todas las columnas de las filas 2 a 4 (inclusive) utilizando loc."""

df_world = pd.read_csv("world-data-2023_part1.csv", index_col = 0) 

df_world


Country Density\r\n(P/Km2) Abbreviation Agricultural Land( %)  \
0    Afghanistan                 60           AF                58.10%   
1        Albania                105           AL                43.10%   
2        Algeria                 18           DZ                17.40%   
3        Andorra                164           AD                40.00%   
4         Angola                 26           AO                47.50%   
..           ...                ...          ...                   ...   
190    Venezuela                 32           VE                24.50%   
191      Vietnam                314           VN                39.30%   
192        Yemen                 56           YE                44.60%   
193       Zambia                 25           ZM                32.10%   
194     Zimbabwe                 38           ZW                41.90%   

    Land Area(Km2) Armed Forces size  Birth Rate  Calling Code  \
0          652,230           323,000       32.49          93.0   
1           28,748             9,000       11.78         355.0   
2        2,381,741           317,000       24.28         213.0   
3              468               NaN        7.20         376.0   
4        1,246,700           117,000       40.73         244.0   
..             ...               ...         ...           ...   
190        912,050           343,000       17.88          58.0   
191        331,210           522,000       16.75          84.0   
192        527,968            40,000       30.45         967.0   
193        752,618            16,000       36.19         260.0   
194        390,757            51,000       30.68         263.0   

    Capital/Major City Co2-Emissions       CPI CPI Change (%) Currency-Code  \
0                Kabul         8,672     149.9          2.30%           AFN   
1               Tirana         4,536    119.05          1.40%           ALL   
2              Algiers       150,006    151.36          2.00%           DZD   
3     Andorra la Vella           469       NaN            NaN           EUR   
4               Luanda        34,693    261.73         17.10%           AOA   
..                 ...           ...       ...            ...           ...   
190            Caracas       164,175  2,740.27        254.90%           VED   
191              Hanoi       192,668    163.52          2.80%           VND   
192              Sanaa        10,609    157.58          8.10%           YER   
193             Lusaka         5,141    212.31          9.20%           ZMW   
194             Harare        10,983    105.51          0.90%           NaN   

     Fertility Rate Forested Area (%) Gasoline Price  
0              4.47             2.10%         $0.70   
1              1.62            28.10%         $1.36   
2              3.02             0.80%         $0.28   
3              1.27            34.00%         $1.51   
4              5.52            46.30%         $0.97   
..              ...               ...            ...  
190            2.27            52.70%         $0.00   
191            2.05            48.10%         $0.80   
192            3.79             1.00%         $0.92   
193            4.63            65.20%         $1.40   
194            3.62            35.50%         $1.34   

[195 rows x 16 columns]

In [ ]:
df_world.loc[2:4]

Country Density\r\n(P/Km2) Abbreviation Agricultural Land( %)  \
2  Algeria                 18           DZ                17.40%   
3  Andorra                164           AD                40.00%   
4   Angola                 26           AO                47.50%   

  Land Area(Km2) Armed Forces size  Birth Rate  Calling Code  \
2      2,381,741           317,000       24.28         213.0   
3            468               NaN        7.20         376.0   
4      1,246,700           117,000       40.73         244.0   

  Capital/Major City Co2-Emissions     CPI CPI Change (%) Currency-Code  \
2            Algiers       150,006  151.36          2.00%           DZD   
3   Andorra la Vella           469     NaN            NaN           EUR   
4             Luanda        34,693  261.73         17.10%           AOA   

   Fertility Rate Forested Area (%) Gasoline Price  
2            3.02             0.80%         $0.28   
3            1.27            34.00%         $1.51   
4            5.52            46.30%         $0.97

In [54]:
"""Utilizando loc, filtra el conjunto de datos para mostrar solo las filas donde la densidad (columna "Birth Rate") es mayor a 30."""

df_world_mayor = df_world.loc[df_world["Birth Rate"] > 30, :]

df_world_mayor

Country Density\r\n(P/Km2) Abbreviation  \
0                         Afghanistan                 60           AF   
4                              Angola                 26           AO   
18                              Benin                108           BJ   
26                       Burkina Faso                 76           BF   
27                            Burundi                463           BI   
28                        Ivory Coast                 83           CI   
31                           Cameroon                 56           CM   
33           Central African Republic                  8           CF   
34                               Chad                 13           TD   
38                            Comoros                467           KM   
39              Republic of the Congo                 16          NaN   
45   Democratic Republic of the Congo                 40           CD   
53                  Equatorial Guinea                 50           GQ   
54                            Eritrea                 35           ER   
57                           Ethiopia                115           ET   
61                              Gabon                  9           GA   
62                         The Gambia                239           GM   
69                             Guinea                 53           GN   
70                      Guinea-Bissau                 70           GW   
96                            Liberia                 53           LR   
101                        Madagascar                 48           MG   
102                            Malawi                203           MW   
105                              Mali                 17           ML   
108                        Mauritania                  5           MR   
117                        Mozambique                 40           MZ   
125                             Niger                 19           NE   
126                           Nigeria                226           NG   
144                            Rwanda                525           RW   
150                      S�����������                228           ST   
152                           Senegal                 87           SN   
155                      Sierra Leone                111           SL   
159                   Solomon Islands                 25           SB   
160                           Somalia                 25           SO   
163                       South Sudan                 18           SS   
166                             Sudan                 25           SD   
171                        Tajikistan                 68           TJ   
172                          Tanzania                 67           TZ   
175                              Togo                152           TG   
182                            Uganda                229           UG   
192                             Yemen                 56           YE   
193                            Zambia                 25           ZM   
194                          Zimbabwe                 38           ZW   

    Agricultural Land( %) Land Area(Km2) Armed Forces size  Birth Rate  \
0                  58.10%        652,230           323,000       32.49   
4                  47.50%      1,246,700           117,000       40.73   
18                 33.30%        112,622            12,000       36.22   
26                 44.20%        274,200            11,000       37.93   
27                 79.20%         27,830            31,000       39.01   
28                 64.80%        322,463            27,000       35.74   
31                 20.60%        475,440            24,000       35.39   
33                  8.20%        622,984             8,000       35.35   
34                 39.70%      1,284,000            35,000       42.17   
38                 71.50%          2,235               NaN       31.88   
39                 31.10%        342,000            12,000       32.86   
45

In [62]:
"""Utilizando loc selecciona las columnas "Country" y "Capital/Major City" de las filas donde el porcentaje de tierra agrícola (columna "Fertility Rate") es superior al 3."""

df_world.loc[df_world["Fertility Rate"] > 3, ["Country", "Capital/Major City"]]

Country Capital/Major City
0                         Afghanistan              Kabul
2                             Algeria            Algiers
4                              Angola             Luanda
18                              Benin         Porto-Novo
26                       Burkina Faso        Ouagadougou
27                            Burundi          Bujumbura
28                        Ivory Coast       Yamoussoukro
31                           Cameroon            Yaound�
33           Central African Republic             Bangui
34                               Chad          N'Djamena
38                            Comoros    Moroni, Comoros
39              Republic of the Congo        Brazzaville
45   Democratic Republic of the Congo           Kinshasa
51                              Egypt              Cairo
53                  Equatorial Guinea             Malabo
54                            Eritrea             Asmara
57                           Ethiopia        Addis Ababa
61                              Gabon         Libreville
62                         The Gambia             Banjul
65                              Ghana              Accra
69                             Guinea            Conakry
70                      Guinea-Bissau             Bissau
80                               Iraq            Baghdad
82                             Israel          Jerusalem
88                              Kenya            Nairobi
89                           Kiribati       South Tarawa
91                         Kyrgyzstan            Bishkek
95                            Lesotho             Maseru
96                            Liberia           Monrovia
101                        Madagascar       Antananarivo
102                            Malawi           Lilongwe
105                              Mali             Bamako
107                  Marshall Islands             Majuro
108                        Mauritania         Nouakchott
111    Federated States of Micronesia            Palikir
117                        Mozambique             Maputo
119                           Namibia           Windhoek
125                             Niger             Niamey
126                           Nigeria              Abuja
131                          Pakistan          Islamabad
135                  Papua New Guinea       Port Moresby
144                            Rwanda             Kigali
148                             Samoa               Apia
150                      S�����������              S����
152                           Senegal              Dakar
155                      Sierra Leone           Freetown
159                   Solomon Islands            Honiara
160                           Somalia          Mogadishu
163                       South Sudan               Juba
166                             Sudan           Khartoum
171                        Tajikistan           Dushanbe
172                          Tanzania             Dodoma
174                        East Timor               Dili
175                              Togo               Lom�
176                             Tonga           Nuku����
182                            Uganda            Kampala
189                           Vanuatu          Port Vila
192                             Yemen              Sanaa
193                            Zambia             Lusaka
194                          Zimbabwe             Harare

In [59]:
df_world.dtypes["Fertility Rate"]

dtype('float64')