PAIR INTRO A PANDAS:

In [42]:
import pandas as pd
import numpy as np
import random

 
1. ¿Qué diferencia hay entre una Serie y un DataFrame?

 Series:
- es una estructura unidimensional (array 1d)
- contiene UN tipo de dato.
- Tiene indice -> pueden ser de distintos tipos (pueden ser numericas, int, ...)
- Propiedades: 
        -> .values
        -> .index
        -> .shape
        -> .size
        -> .dtype

 DATAFRAMES:

- Dos dimensiones
- Cada columna tiene un tipo de dato
- Tiene indice.
- Propiedades:
    -> .size
    -> .shape
    -> .columns

In [43]:
# Es el turno de los DataFrames
# Crea un array de dos dimensiones con 4 filas y 3 columnas.

array = np.random.randint(1,50, (4,3))

print(f"El array bidimensional creado a partir del método np.random.randint(): \n  {array} \n")


El array bidimensional creado a partir del método np.random.randint(): 
  [[23 29 31]
 [ 4 13  7]
 [33 49 11]
 [29 18  7]] 



In [44]:
#Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

df_paises = pd.DataFrame(array)

In [45]:
df_paises

0   1   2
0  23  29  31
1   4  13   7
2  33  49  11
3  29  18   7

In [46]:
paises = ["España", "Francia", "Italia"]

df_paises = pd.DataFrame(array, columns=[paises])

df_paises

España Francia Italia
0     23      29     31
1      4      13      7
2     33      49     11
3     29      18      7

In [47]:
# Descarga el archivo "medallas" y carga el DataFrame.

df_medallas = pd.read_csv("medallas.csv", index_col = 0) # tb podemos poner index_col= "País"

df_medallas

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [48]:
# Usando el loc extrae todas las columnas de la fila de Tailandia.

df_medallas.loc[df_medallas["País"] == "Tailandia"]

País  Oro  Plata  Bronce
7  Tailandia  132    175     278

In [49]:
#Usando el loc extrae todas las columnas de China e Irán.

df_medallas.loc[df_medallas["País"] == "China"] 

País   Oro  Plata  Bronce
1  China  1473    994     720

In [50]:
df_medallas.loc[df_medallas["País"] == "Irán"] 

País  Oro  Plata  Bronce
4  Irán  179    181     197

In [51]:
"""df_medallas = df_medallas.loc[(df_medallas["País"] == "China") & (df_medallas["País"]=="tailandia")]
df_medallas"""

'df_medallas = df_medallas.loc[(df_medallas["País"] == "China") & (df_medallas["País"]=="tailandia")]\ndf_medallas'

In [52]:
df_medallas.loc[[1,4]]

País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197

In [53]:
# Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

df_medallas.loc[[1,4]]

País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197

In [55]:
# Usando el iloc extrae la información de la India. Devolved todas las columnas.

df_medallas.iloc[5:6]

País  Oro  Plata  Bronce
6  India  154    202     315

In [ ]:
# Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

df_medallas.iloc[1::2]

País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235

In [57]:
# Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

df_medallas.iloc[1::2, [1,2,3]]

Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235

In [58]:
# ¿Qué país consiguió más de 200 medallas de oro?

df_medallas ["Oro"] > 200

1      True
2      True
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
Name: Oro, dtype: bool

In [59]:
df_medallas[df_medallas["Oro"] > 200] 

País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827

In [62]:
# ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

df_medallas[(df_medallas["Oro"] > 200) & (df_medallas["Plata"] > 1000)]

País   Oro  Plata  Bronce
2  Japón  1032   1037     985

In [63]:
# ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

df_medallas[(df_medallas["Oro"] > 200) & (df_medallas["Bronce"] > 700)]


País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827

In [65]:
# Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

df_medallas["Total"] = df_medallas["Oro"] + df_medallas["Plata"] + df_medallas ["Bronce"]
df_medallas


País   Oro  Plata  Bronce  Total
1             China  1473    994     720   3187
2             Japón  1032   1037     985   3054
3     Corea del Sur   745    663     827   2235
4              Irán   179    181     197    557
5        Kazajistán   155    158     224    537
6             India   154    202     315    671
7         Tailandia   132    175     278    585
8         Indonesia   112    131     240    483
9      China Taipéi    99    144     276    519
10  Corea del Norte    91    120     235    446

In [69]:
# 3.Momento de trabajar con Series. Contesta a las siguientes preguntas:
# Crea dos listas:
# Una que se llame "valores" que tenga 7 números aleatorios.
# Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

valores = np.random.randint(1,50, 7)

indices = ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"]


In [71]:
"""A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie
y la variable indices sean los índices de la Serie."""

serie_dias = pd.Series(valores, index = indices )
serie_dias

lunes        15
martes       10
miercoles    16
jueves       32
viernes      12
sabado       10
domingo      36
dtype: int64

In [ ]:
"""A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip 
que nos permite iterar por dos listas a la vez. Más información sobre este método aquí."""

diccionario = {}

In [ ]:
dict(zip(indices,valores)) # nos piden diccionario

{'lunes': np.int64(15),
 'martes': np.int64(10),
 'miercoles': np.int64(16),
 'jueves': np.int64(32),
 'viernes': np.int64(12),
 'sabado': np.int64(10),
 'domingo': np.int64(36)}

In [78]:
diccionario ={}
for e in zip(indices,valores):
    diccionario[e[0]]= e[1]
   
diccionario

{'lunes': np.int64(15),
 'martes': np.int64(10),
 'miercoles': np.int64(16),
 'jueves': np.int64(32),
 'viernes': np.int64(12),
 'sabado': np.int64(10),
 'domingo': np.int64(36)}

In [ ]:
zip(indices,valores) 