In [3]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\InvitadoLaptop\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

## Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [5]:
arr_1 = np.random.randint(10,99, (50))
arr_1

array([17, 40, 42, 91, 97, 16, 40, 26, 15, 65, 95, 22, 50, 95, 27, 67, 62,
       46, 77, 12, 70, 68, 51, 41, 91, 69, 50, 87, 87, 21, 68, 73, 27, 37,
       51, 38, 57, 56, 46, 36, 72, 13, 23, 82, 90, 93, 26, 37, 76, 23],
      dtype=int32)

In [6]:
arr_1.size

50

In [7]:
arr_1 % 5 == 0

array([False,  True, False, False, False, False,  True, False,  True,
        True,  True, False,  True,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False])

In [8]:
arr_1[arr_1 % 5 == 0]

array([40, 40, 15, 65, 95, 50, 95, 70, 50, 90], dtype=int32)

2. Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [9]:
arr_2 = np.random.randint(1,21, (30))
arr_2

array([ 8, 13,  6,  7, 13, 12, 10, 13, 20,  8,  3,  2,  1,  4,  3, 14, 17,
        3,  8, 14, 17, 19, 14, 18, 10,  4,  4, 18,  2,  9], dtype=int32)

In [10]:
arr_2[1::2]

array([13,  7, 12, 13,  8,  2,  4, 14,  3, 14, 19, 18,  4, 18,  9],
      dtype=int32)

3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [11]:
arr_3 = np.random.rand(4,6)+10
arr_3

array([[10.29349037, 10.80085597, 10.97443576, 10.41199241, 10.80737828,
        10.19355753],
       [10.7277553 , 10.29814462, 10.4562218 , 10.19958382, 10.82367238,
        10.77749193],
       [10.50894055, 10.34942722, 10.40055679, 10.83623117, 10.46186748,
        10.15827606],
       [10.19562654, 10.24647202, 10.04992829, 10.59974395, 10.26344464,
        10.33591825]])

In [12]:
np.round(arr_3, 2)

array([[10.29, 10.8 , 10.97, 10.41, 10.81, 10.19],
       [10.73, 10.3 , 10.46, 10.2 , 10.82, 10.78],
       [10.51, 10.35, 10.4 , 10.84, 10.46, 10.16],
       [10.2 , 10.25, 10.05, 10.6 , 10.26, 10.34]])

# Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [13]:
arr_4 = np.random.rand(2,3,5)
arr_4

array([[[0.09969975, 0.68238541, 0.8540227 , 0.84611394, 0.65843928],
        [0.32648865, 0.48847655, 0.73849479, 0.77492066, 0.98139015],
        [0.86325714, 0.03906446, 0.33051593, 0.83896188, 0.67498549]],

       [[0.1092756 , 0.08781604, 0.95413674, 0.87759189, 0.56824319],
        [0.41298475, 0.66078607, 0.25656485, 0.77829399, 0.57274039],
        [0.80627706, 0.57127858, 0.38868961, 0.58419937, 0.98763707]]])

In [14]:
arr_4_2=np.round(arr_4, 1)

arr_4_2

array([[[0.1, 0.7, 0.9, 0.8, 0.7],
        [0.3, 0.5, 0.7, 0.8, 1. ],
        [0.9, 0. , 0.3, 0.8, 0.7]],

       [[0.1, 0.1, 1. , 0.9, 0.6],
        [0.4, 0.7, 0.3, 0.8, 0.6],
        [0.8, 0.6, 0.4, 0.6, 1. ]]])

2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

**Si el valor del array es igual que la media, se reemplaza por "A".

**Si el valor del array es mayor que la media, se reemplaza por "B".

**Si el valor del array es menor que la media, se reemplaza por "C".

**Si el valor es igual que el máximo, se reemplaza por "D".

**Si el valor es igual que el mínimo, se reemplaza por "E".

In [ ]:
# a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
    [0.1, 0.9, 0.6, 0.1, 0.2],
    [1. , 0.2, 0.1, 0.8, 0.3]],

[[0. , 0.3, 0.4, 0.5, 0.1],
    [0.5, 0.7, 0.9, 0. , 0.8],
    [0.5, 0.3, 0.5, 0.8, 0.1]]])

# sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

# nuestro array vacío debería quedar como este: 
[[["A", "B", "C", "B", "C"],
    ["C", "B", "B", "C", "C"],
    ["D" , "C", "C", "B", "C"]],

[["E" , "C", "A", "B", "C"],
    ["B", "B","B", "E" , "B"],
    ["B", "C", "B", "B", "C"]]])

In [16]:
media=np.mean(arr_4_2)
media

np.float64(0.6033333333333334)

In [17]:
media_2=np.round(media,1)
media_2

np.float64(0.6)

In [18]:
vacio=np.empty(arr_4_2.shape, dtype=str)
vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [19]:
A=np.where(arr_4_2 == media_2, "A", vacio)

print(A)

[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' 'A']
  ['' '' '' '' 'A']
  ['' 'A' '' 'A' '']]]


In [20]:
B=np.where(arr_4_2 > media_2, "B" , vacio)
print(B)

[[['' 'B' 'B' 'B' 'B']
  ['' '' 'B' 'B' 'B']
  ['B' '' '' 'B' 'B']]

 [['' '' 'B' 'B' '']
  ['' 'B' '' 'B' '']
  ['B' '' '' '' 'B']]]


In [21]:
C=np.where(arr_4_2 < media_2, "C" , vacio)
print(C)

[[['C' '' '' '' '']
  ['C' 'C' '' '' '']
  ['' 'C' 'C' '' '']]

 [['C' 'C' '' '' '']
  ['C' '' 'C' '' '']
  ['' '' 'C' '' '']]]


In [22]:
max=np.max(arr_4_2)
max

np.float64(1.0)

In [23]:
D=np.where(arr_4_2 == max, "D" , vacio)
print(D)

[[['' '' '' '' '']
  ['' '' '' '' 'D']
  ['' '' '' '' '']]

 [['' '' 'D' '' '']
  ['' '' '' '' '']
  ['' '' '' '' 'D']]]


In [24]:
min=np.min(arr_4_2)
min

np.float64(0.0)

In [25]:
E=np.where(arr_4_2 == min, "E" , vacio)
print(E)

[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' 'E' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]


In [26]:
TOTAL=A+B+C+D+E
TOTAL

array([[['C', 'B', 'B', 'B', 'B'],
        ['C', 'C', 'B', 'B', 'BD'],
        ['B', 'CE', 'C', 'B', 'B']],

       [['C', 'C', 'BD', 'B', 'A'],
        ['C', 'B', 'C', 'B', 'A'],
        ['B', 'A', 'C', 'A', 'BD']]], dtype='<U5')

# Si te queda tiempo, puedes hacer los siguientes ejercicios:

1. Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [27]:
arr_5 = np.random.randint(0,101, (2, 3, 5))
arr_5

array([[[66, 13, 42,  6, 61],
        [40, 46, 10, 82,  2],
        [50, 74, 42, 59, 30]],

       [[13, 50, 21, 47, 42],
        [80, 50, 91, 46, 65],
        [22, 14, 28, 54, 31]]], dtype=int32)

In [28]:
arr_5 % 3 == 0

array([[[ True, False,  True,  True, False],
        [False, False, False, False, False],
        [False, False,  True, False,  True]],

       [[False, False,  True, False,  True],
        [False, False, False, False, False],
        [False, False, False,  True, False]]])

In [29]:
arr_5[arr_5 % 3 == 0]

array([66, 42,  6, 42, 30, 21, 42, 54], dtype=int32)

In [30]:
arr_5_2=np.where(arr_5 % 3 == 0, 0 , arr_5)
print(arr_5_2)

[[[ 0 13  0  0 61]
  [40 46 10 82  2]
  [50 74  0 59  0]]

 [[13 50  0 47  0]
  [80 50 91 46 65]
  [22 14 28  0 31]]]


2. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [31]:
arr_6 = np.random.randint(0,101, (2, 3, 4))
arr_6

array([[[30, 64, 29, 45],
        [ 5, 49, 92, 52],
        [90,  4, 84, 62]],

       [[56, 47, 26, 11],
        [52, 72, 98, 57],
        [35, 20, 82, 35]]], dtype=int32)

In [32]:
reshaped_a = np.reshape(arr_6, (6, 4))
print(f"El array después de aplicar el método 'np.reshape()' es: \n {reshaped_a}")


El array después de aplicar el método 'np.reshape()' es: 
 [[30 64 29 45]
 [ 5 49 92 52]
 [90  4 84 62]
 [56 47 26 11]
 [52 72 98 57]
 [35 20 82 35]]


3. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [33]:
arr_7 = np.random.randint(1,61, (3, 4, 5))
arr_7

array([[[31, 39, 14, 44, 31],
        [10, 27, 60, 12, 15],
        [ 7, 20, 40,  3, 49],
        [23, 27, 16, 13, 53]],

       [[31, 23,  7,  7, 50],
        [34, 46,  7,  9, 41],
        [ 4, 36, 56,  2, 44],
        [25,  8, 22, 17, 38]],

       [[33, 15,  7, 16, 23],
        [14, 37, 33, 15, 55],
        [56, 53, 15, 31, 42],
        [58, 54, 53, 40, 30]]], dtype=int32)

In [ ]:
reshaped_b = np.reshape(arr_7, (10, 6))
print(f"El array después de aplicar el método 'np.reshape()' es: \n {reshaped_b}")

El array después de aplicar el método 'np.reshape()' es: 
 [[31 39 14 44 31 10]
 [27 60 12 15  7 20]
 [40  3 49 23 27 16]
 [13 53 31 23  7  7]
 [50 34 46  7  9 41]
 [ 4 36 56  2 44 25]
 [ 8 22 17 38 33 15]
 [ 7 16 23 14 37 33]
 [15 55 56 53 15 31]
 [42 58 54 53 40 30]]


4. Utiliza el array 3D del ejercicio anterior de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [46]:
tridimensional_trans_defecto = np.transpose(arr_7, (2, 1, 0))
print(f"El array después de aplicar el método 'np.transpose()': \n {tridimensional_trans_defecto}")

El array después de aplicar el método 'np.transpose()': 
 [[[31 31 33]
  [10 34 14]
  [ 7  4 56]
  [23 25 58]]

 [[39 23 15]
  [27 46 37]
  [20 36 53]
  [27  8 54]]

 [[14  7  7]
  [60  7 33]
  [40 56 15]
  [16 22 53]]

 [[44  7 16]
  [12  9 15]
  [ 3  2 31]
  [13 17 40]]

 [[31 50 23]
  [15 41 55]
  [49 44 42]
  [53 38 30]]]


5. Utiliza el array 3D del ejercicio anterior 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [54]:
tridimensional_trans_defecto2 = np.transpose(reshaped_b,(2,0,1))
print(f"El array después de aplicar el método 'np.transpose()': \n {tridimensional_trans_defecto2}")

ValueError: axes don't match array